import request from 'supertest';
import express, { Application } from 'express';
import mongoose from 'mongoose';
import disputeRoutes from '../../routes/disputeRoutes';
import Dispute, { DisputeStatus } from '../../models/Dispute';
import Order, { OrderStatus } from '../../models/Order';
import User, { UserRole } from '../../models/User';
import { errorHandler } from '../../middlewares/errorHandler';
import { generateAccessToken } from '../../utils/jwt';

const app: Application = express();
app.use(express.json());
app.use('/api/disputes', disputeRoutes);
app.use(errorHandler);

describe('Dispute API (Integration)', () => {

    const complainerId = new mongoose.Types.ObjectId();
    const mockComplainerToken = generateAccessToken(complainerId, 'complainer@test.com', 'Buyer');
    const authHeader = `Bearer ${mockComplainerToken}`;

    beforeEach(async () => {
        await User.create({
            id: complainerId.toString(),
            name: 'Angry Buyer',
            mobile_number: '9333333331',
            role: UserRole.BUYER,
            is_verified: true,
            is_telegram_linked: false,
            aadhaar_verified: true,
            business_verified: true
        });
    });

    it('should let a user raise a dispute against an order successfully', async () => {
        const orderId = new mongoose.Types.ObjectId().toString();
        // Seed physical order so controller 404 block doesn't hit
        await Order.create({
            id: orderId,
            crop_listing_id: new mongoose.Types.ObjectId().toString(),
            buyer_user_id: complainerId.toString(),
            sender_user_id: new mongoose.Types.ObjectId().toString(),
            final_price: 100,
            quantity: 10,
            status: OrderStatus.CREATED,
            payment_status: 'PAID'
        });

        const payload = {
            order_id: orderId,
            description: 'My apples arrived utterly destroyed!'
        };

        const res = await request(app)
            .post('/api/disputes')
            .set('Authorization', authHeader)
            .send(payload);

        expect(res.status).toBe(201);
        expect(res.body.success).toBe(true);
        expect(res.body.data.status).toBe(DisputeStatus.OPEN);
        expect(res.body.data.description).toBe('My apples arrived utterly destroyed!');

        const fromDb = await Dispute.findOne({ order_id: orderId });
        expect(fromDb).not.toBeNull();
    });

    it('should correctly fetch disputes natively generated by the caller', async () => {
        await Dispute.create([
            {
                id: new mongoose.Types.ObjectId().toString(),
                order_id: new mongoose.Types.ObjectId().toString(),
                raised_by_user_id: complainerId.toString(),
                description: 'Issue one',
                status: DisputeStatus.OPEN
            },
            {
                id: new mongoose.Types.ObjectId().toString(),
                order_id: new mongoose.Types.ObjectId().toString(),
                raised_by_user_id: complainerId.toString(),
                description: 'Issue two',
                status: DisputeStatus.UNDER_REVIEW
            }
        ]);

        const res = await request(app)
            .get('/api/disputes')
            .set('Authorization', authHeader);

        expect(res.status).toBe(200);
        expect(res.body.success).toBe(true);
        expect(res.body.data.length).toBe(2);
    });

    it('should resolve the dispute correctly and update its state safely', async () => {
        const targetId = new mongoose.Types.ObjectId().toString();

        await Dispute.create({
            id: targetId,
            order_id: new mongoose.Types.ObjectId().toString(),
            raised_by_user_id: complainerId.toString(),
            description: 'Fix my thing',
            status: DisputeStatus.OPEN
        });

        const res = await request(app)
            .patch(`/api/disputes/${targetId}/status`)
            .set('Authorization', authHeader)
            .send({ status: DisputeStatus.RESOLVED });

        expect(res.status).toBe(200);
        expect(res.body.success).toBe(true);
        expect(res.body.data.status).toBe(DisputeStatus.RESOLVED);

        const checkDb = await Dispute.findOne({ id: targetId });
        expect(checkDb!.status).toBe(DisputeStatus.RESOLVED);
    });
});
